apiVersion: v1
kind: Service
metadata: 
  name: adguard 
  namespace: adguard
  labels: 
    app: adguard 
spec: 
  type: LoadBalancer
  loadBalancerIP: 10.100.15.101
  selector: 
    app: adguard 
  ports: 
  - port: 53
    targetPort: 53
