apiVersion: v1
kind: PersistentVolumeClaim 
metadata: 
  namespace: adguard 
  name: adguard-data 
  labels: 
    app: adguard 
spec: 
  volumeName: "adguard-data" 
  accessModes: 
  - ReadWriteMany 
  resources: 
    requests: 
      storage: "1Gi"
