apiVersion: v1 
kind: PersistentVolume
metadata: 
  name: adguard-data
  labels: 
    app: adguard
spec: 
  storageClassName: "manual" 
  capacity: 
    storage: "1Gi" 
  accessModes: 
  - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  hostPath: 
    path: "/home/sistemas/mountpoints/adguard-data"
